---
output:
  html_document: default
  pdf_document: default
  word_document: default
---


<a id="top"></a>

# multiSeg Vignette
### Vincent Runge
#### LaMME Evry November 21, 2017

> [Introduction](#intro)

> [Pruning](#pr)

<a id="intro"></a>

## Introduction

Installation of the package througth its github repository
```{r}
devtools::install_github("vrunge/multiSeg", force = TRUE)
```

Loading the package 
```{r}
library(multiSeg)
```

Choosing parameters to simulate data. 
```{r}
n <- 500
var <- 1
means <- matrix(c(0,1,2,1,0,1,2,2,0,0,1,1),3,4)
changes <- c(0.3,0.6,1)
```

Data simulation
```{r}
data <- dataG(n,means,changes, var)
head(data)
```

Segmentation algorithm
```{r}
file = paste(getwd(),"/dataG.txt",sep = "")
res <- multiSeg(file,4*2*log(n),3)
```

Plots
```{r}
pruning(res)
segmentation(file,res)
changepoints(res)
```

<a id="pr"></a>

## Pruning

```{r}
n <- 500
var <- 1
means <- matrix(c(0,1,2,1,0,1,2,2,0,0,1,1),3,4)
changes <- c(0.3,0.6,1)
data <- dataG(n,means,changes, var)
file = paste(getwd(),"/dataG.txt",sep = "")

```

```{r}
res <- multiSeg(file,4*2*log(n),0)
pruning(res)
```

```{r}
res <- multiSeg(file,4*2*log(n),1)
pruning(res)
```

```{r}
res <- multiSeg(file,4*2*log(n),2)
pruning(res)
```


```{r}
res <- multiSeg(file,4*2*log(n),3)
pruning(res)
```

[Back to Top](#top)
