// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// transfert
List transfert(std::string file, double beta, int type, int show);
RcppExport SEXP _multiSeg_transfert(SEXP fileSEXP, SEXP betaSEXP, SEXP typeSEXP, SEXP showSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type show(showSEXP);
    rcpp_result_gen = Rcpp::wrap(transfert(file, beta, type, show));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multiSeg_transfert", (DL_FUNC) &_multiSeg_transfert, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_multiSeg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
