// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// transfert
List transfert(std::string file, double beta, int type, int show);
RcppExport SEXP multiSeg_transfert(SEXP fileSEXP, SEXP betaSEXP, SEXP typeSEXP, SEXP showSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type show(showSEXP);
    __result = Rcpp::wrap(transfert(file, beta, type, show));
    return __result;
END_RCPP
}
